// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: order/v1/order.proto

package orderv1

import (
	v1 "github.com/Anabol1ks/orderhub-pkg-proto/proto/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Единица позиции заказа (в ответах)
type OrderItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity       uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,3,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"` // цена за штуку в мин. единицах валюты
	LineTotalCents int64                  `protobuf:"varint,4,opt,name=line_total_cents,json=lineTotalCents,proto3" json:"line_total_cents,omitempty"` // unit_price_cents * quantity
	CurrencyCode   string                 `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`          // ISO-4217 (например "USD", "EUR", "RUB")
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderItem) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *OrderItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *OrderItem) GetLineTotalCents() int64 {
	if x != nil {
		return x.LineTotalCents
	}
	return 0
}

func (x *OrderItem) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

// Входная позиция при создании (цены сервер может игнорировать/пересчитать)
type OrderItemInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemInput) Reset() {
	*x = OrderItemInput{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemInput) ProtoMessage() {}

func (x *OrderItemInput) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemInput.ProtoReflect.Descriptor instead.
func (*OrderItemInput) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItemInput) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *OrderItemInput) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// Сущность заказа
type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              *v1.UUID               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          *v1.UUID               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          v1.OrderStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=orderhub.common.v1.OrderStatus" json:"status,omitempty"`
	Items           []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	TotalPriceCents int64                  `protobuf:"varint,5,opt,name=total_price_cents,json=totalPriceCents,proto3" json:"total_price_cents,omitempty"` // сумма по позициям
	CurrencyCode    string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	CancelReason    string                 `protobuf:"bytes,7,opt,name=cancel_reason,json=cancelReason,proto3" json:"cancel_reason,omitempty"` // если CANCELLED — краткая причина (необязательно)
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() *v1.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Order) GetUserId() *v1.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Order) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalPriceCents() int64 {
	if x != nil {
		return x.TotalPriceCents
	}
	return 0
}

func (x *Order) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Order) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// минимум одна позиция
	Items []*OrderItemInput `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// идемпотенси-ключ (рекомендовано): одинаковый ключ -> повтор одного и того же заказа
	Comment       string `protobuf:"bytes,10,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetItems() []*OrderItemInput {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreateOrderRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.UUID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderRequest) GetOrderId() *v1.UUID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// пагинация (простая): limit/offset; по умолчанию user_id берём из JWT в интерсепторе
	Limit  int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// опциональный фильтр по статусу
	Status v1.OrderStatus `protobuf:"varint,3,opt,name=status,proto3,enum=orderhub.common.v1.OrderStatus" json:"status,omitempty"`
	// только для админов: смотреть заказы конкретного пользователя
	UserId        *v1.UUID `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // опционально
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOrdersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() v1.OrderStatus {
	if x != nil {
		return x.Status
	}
	return v1.OrderStatus(0)
}

func (x *ListOrdersRequest) GetUserId() *v1.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                             // общее кол-во (для построения пагинации)
	NextOffset    int32                  `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"` // offset для следующей страницы (или = -1 если больше нет)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResponse) GetNextOffset() int32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.UUID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *CancelOrderRequest) GetOrderId() *v1.UUID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *CancelOrderRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\"\xfa\x01\n" +
	"\tOrderItem\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\x12'\n" +
	"\bquantity\x18\x02 \x01(\rB\v\xfaB\b*\x06\x18\xa0\x8d\x06 \x00R\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x03 \x01(\x03R\x0eunitPriceCents\x12(\n" +
	"\x10line_total_cents\x18\x04 \x01(\x03R\x0elineTotalCents\x12-\n" +
	"\rcurrency_code\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\fcurrencyCode\"x\n" +
	"\x0eOrderItemInput\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\rB\a\xfaB\x04*\x02 \x00R\bquantity\"\xd2\x03\n" +
	"\x05Order\x122\n" +
	"\x02id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x02id\x12;\n" +
	"\auser_id\x18\x02 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06userId\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.orderhub.common.v1.OrderStatusR\x06status\x12)\n" +
	"\x05items\x18\x04 \x03(\v2\x13.order.v1.OrderItemR\x05items\x12*\n" +
	"\x11total_price_cents\x18\x05 \x01(\x03R\x0ftotalPriceCents\x12-\n" +
	"\rcurrency_code\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\fcurrencyCode\x12#\n" +
	"\rcancel_reason\x18\a \x01(\tR\fcancelReason\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"r\n" +
	"\x12CreateOrderRequest\x128\n" +
	"\x05items\x18\x01 \x03(\v2\x18.order.v1.OrderItemInputB\b\xfaB\x05\x92\x01\x02\b\x01R\x05items\x12\"\n" +
	"\acomment\x18\n" +
	" \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\acomment\"<\n" +
	"\x13CreateOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"P\n" +
	"\x0fGetOrderRequest\x12=\n" +
	"\border_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aorderId\"9\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"\xc1\x01\n" +
	"\x11ListOrdersRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x06offset\x127\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1f.orderhub.common.v1.OrderStatusR\x06status\x121\n" +
	"\auser_id\x18\x04 \x01(\v2\x18.orderhub.common.v1.UUIDR\x06userId\"t\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\x05R\n" +
	"nextOffset\"u\n" +
	"\x12CancelOrderRequest\x12=\n" +
	"\border_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aorderId\x12 \n" +
	"\x06reason\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x18\xf4\x03R\x06reason\"<\n" +
	"\x13CancelOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order2\xb2\x02\n" +
	"\fOrderService\x12J\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x1d.order.v1.CreateOrderResponse\x12A\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x1a.order.v1.GetOrderResponse\x12G\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\x12J\n" +
	"\vCancelOrder\x12\x1c.order.v1.CancelOrderRequest\x1a\x1d.order.v1.CancelOrderResponseB@Z>github.com/Anabol1ks/orderhub-pkg-proto/proto/order/v1;orderv1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_order_v1_order_proto_goTypes = []any{
	(*OrderItem)(nil),             // 0: order.v1.OrderItem
	(*OrderItemInput)(nil),        // 1: order.v1.OrderItemInput
	(*Order)(nil),                 // 2: order.v1.Order
	(*CreateOrderRequest)(nil),    // 3: order.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),   // 4: order.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),       // 5: order.v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 6: order.v1.GetOrderResponse
	(*ListOrdersRequest)(nil),     // 7: order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),    // 8: order.v1.ListOrdersResponse
	(*CancelOrderRequest)(nil),    // 9: order.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),   // 10: order.v1.CancelOrderResponse
	(*v1.UUID)(nil),               // 11: orderhub.common.v1.UUID
	(v1.OrderStatus)(0),           // 12: orderhub.common.v1.OrderStatus
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_order_v1_order_proto_depIdxs = []int32{
	11, // 0: order.v1.OrderItem.product_id:type_name -> orderhub.common.v1.UUID
	11, // 1: order.v1.OrderItemInput.product_id:type_name -> orderhub.common.v1.UUID
	11, // 2: order.v1.Order.id:type_name -> orderhub.common.v1.UUID
	11, // 3: order.v1.Order.user_id:type_name -> orderhub.common.v1.UUID
	12, // 4: order.v1.Order.status:type_name -> orderhub.common.v1.OrderStatus
	0,  // 5: order.v1.Order.items:type_name -> order.v1.OrderItem
	13, // 6: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	13, // 7: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 8: order.v1.CreateOrderRequest.items:type_name -> order.v1.OrderItemInput
	2,  // 9: order.v1.CreateOrderResponse.order:type_name -> order.v1.Order
	11, // 10: order.v1.GetOrderRequest.order_id:type_name -> orderhub.common.v1.UUID
	2,  // 11: order.v1.GetOrderResponse.order:type_name -> order.v1.Order
	12, // 12: order.v1.ListOrdersRequest.status:type_name -> orderhub.common.v1.OrderStatus
	11, // 13: order.v1.ListOrdersRequest.user_id:type_name -> orderhub.common.v1.UUID
	2,  // 14: order.v1.ListOrdersResponse.orders:type_name -> order.v1.Order
	11, // 15: order.v1.CancelOrderRequest.order_id:type_name -> orderhub.common.v1.UUID
	2,  // 16: order.v1.CancelOrderResponse.order:type_name -> order.v1.Order
	3,  // 17: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	5,  // 18: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	7,  // 19: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	9,  // 20: order.v1.OrderService.CancelOrder:input_type -> order.v1.CancelOrderRequest
	4,  // 21: order.v1.OrderService.CreateOrder:output_type -> order.v1.CreateOrderResponse
	6,  // 22: order.v1.OrderService.GetOrder:output_type -> order.v1.GetOrderResponse
	8,  // 23: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersResponse
	10, // 24: order.v1.OrderService.CancelOrder:output_type -> order.v1.CancelOrderResponse
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
