// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: inventory/v1/inventory.proto

package inventoryv1

import (
	v1 "github.com/Anabol1ks/orderhub-pkg-proto/proto/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *v1.UUID               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VendorId      *v1.UUID               `protobuf:"bytes,2,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,6,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,7,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() *v1.UUID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Product) GetVendorId() *v1.UUID {
	if x != nil {
		return x.VendorId
	}
	return nil
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *Product) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ProductInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      *v1.UUID               `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    int64                  `protobuf:"varint,5,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	CurrencyCode  string                 `protobuf:"bytes,6,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductInput) Reset() {
	*x = ProductInput{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInput) ProtoMessage() {}

func (x *ProductInput) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInput.ProtoReflect.Descriptor instead.
func (*ProductInput) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ProductInput) GetVendorId() *v1.UUID {
	if x != nil {
		return x.VendorId
	}
	return nil
}

func (x *ProductInput) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ProductInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductInput) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *ProductInput) GetCurrencyCode() string {
	if x != nil {
		return x.CurrencyCode
	}
	return ""
}

func (x *ProductInput) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type ProductPatch struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Sku           *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents    *wrapperspb.Int64Value  `protobuf:"bytes,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	CurrencyCode  *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=currency_code,json=currencyCode,proto3" json:"currency_code,omitempty"`
	IsActive      *wrapperspb.BoolValue   `protobuf:"bytes,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPatch) Reset() {
	*x = ProductPatch{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPatch) ProtoMessage() {}

func (x *ProductPatch) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPatch.ProtoReflect.Descriptor instead.
func (*ProductPatch) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *ProductPatch) GetSku() *wrapperspb.StringValue {
	if x != nil {
		return x.Sku
	}
	return nil
}

func (x *ProductPatch) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ProductPatch) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *ProductPatch) GetPriceCents() *wrapperspb.Int64Value {
	if x != nil {
		return x.PriceCents
	}
	return nil
}

func (x *ProductPatch) GetCurrencyCode() *wrapperspb.StringValue {
	if x != nil {
		return x.CurrencyCode
	}
	return nil
}

func (x *ProductPatch) GetIsActive() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsActive
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductInput          `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CreateProductRequest) GetProduct() *ProductInput {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Patch         *ProductPatch          `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateProductRequest) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *UpdateProductRequest) GetPatch() *ProductPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteProductRequest) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductRequest) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VendorId      *v1.UUID               `protobuf:"bytes,1,opt,name=vendor_id,json=vendorId,proto3" json:"vendor_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	OnlyActive    bool                   `protobuf:"varint,3,opt,name=only_active,json=onlyActive,proto3" json:"only_active,omitempty"`
	Limit         int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsRequest) GetVendorId() *v1.UUID {
	if x != nil {
		return x.VendorId
	}
	return nil
}

func (x *ListProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ListProductsRequest) GetOnlyActive() bool {
	if x != nil {
		return x.OnlyActive
	}
	return false
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextOffset    int32                  `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetNextOffset() int32 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

type BatchGetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []*v1.UUID             `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProductsRequest) Reset() {
	*x = BatchGetProductsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProductsRequest) ProtoMessage() {}

func (x *BatchGetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProductsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetProductsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *BatchGetProductsRequest) GetProductIds() []*v1.UUID {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type BatchGetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetProductsResponse) Reset() {
	*x = BatchGetProductsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetProductsResponse) ProtoMessage() {}

func (x *BatchGetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetProductsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetProductsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *BatchGetProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Stock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Available     int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Reserved      int32                  `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *Stock) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *Stock) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *Stock) GetReserved() int32 {
	if x != nil {
		return x.Reserved
	}
	return 0
}

func (x *Stock) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *GetStockRequest) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

type GetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockResponse) Reset() {
	*x = GetStockResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockResponse) ProtoMessage() {}

func (x *GetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockResponse.ProtoReflect.Descriptor instead.
func (*GetStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *GetStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type SetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Available     int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStockRequest) Reset() {
	*x = SetStockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockRequest) ProtoMessage() {}

func (x *SetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockRequest.ProtoReflect.Descriptor instead.
func (*SetStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *SetStockRequest) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *SetStockRequest) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

type SetStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStockResponse) Reset() {
	*x = SetStockResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStockResponse) ProtoMessage() {}

func (x *SetStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStockResponse.ProtoReflect.Descriptor instead.
func (*SetStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{18}
}

func (x *SetStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type AdjustStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Delta         int32                  `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"` // может быть отрицательным/положительным
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustStockRequest) Reset() {
	*x = AdjustStockRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockRequest) ProtoMessage() {}

func (x *AdjustStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockRequest.ProtoReflect.Descriptor instead.
func (*AdjustStockRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{19}
}

func (x *AdjustStockRequest) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *AdjustStockRequest) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

type AdjustStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stock         *Stock                 `protobuf:"bytes,1,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdjustStockResponse) Reset() {
	*x = AdjustStockResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdjustStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdjustStockResponse) ProtoMessage() {}

func (x *AdjustStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdjustStockResponse.ProtoReflect.Descriptor instead.
func (*AdjustStockResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{20}
}

func (x *AdjustStockResponse) GetStock() *Stock {
	if x != nil {
		return x.Stock
	}
	return nil
}

type ReserveItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveItem) Reset() {
	*x = ReserveItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveItem) ProtoMessage() {}

func (x *ReserveItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveItem.ProtoReflect.Descriptor instead.
func (*ReserveItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{21}
}

func (x *ReserveItem) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *ReserveItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.UUID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*ReserveItem         `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{22}
}

func (x *ReserveRequest) GetOrderId() *v1.UUID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

func (x *ReserveRequest) GetItems() []*ReserveItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReserveOkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveOkItem) Reset() {
	*x = ReserveOkItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveOkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveOkItem) ProtoMessage() {}

func (x *ReserveOkItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveOkItem.ProtoReflect.Descriptor instead.
func (*ReserveOkItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{23}
}

func (x *ReserveOkItem) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *ReserveOkItem) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ReserveFailedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *v1.UUID               `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Requested     string                 `protobuf:"bytes,2,opt,name=requested,proto3" json:"requested,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveFailedItem) Reset() {
	*x = ReserveFailedItem{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveFailedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveFailedItem) ProtoMessage() {}

func (x *ReserveFailedItem) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveFailedItem.ProtoReflect.Descriptor instead.
func (*ReserveFailedItem) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{24}
}

func (x *ReserveFailedItem) GetProductId() *v1.UUID {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *ReserveFailedItem) GetRequested() string {
	if x != nil {
		return x.Requested
	}
	return ""
}

func (x *ReserveFailedItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OkItems       []*ReserveOkItem       `protobuf:"bytes,1,rep,name=ok_items,json=okItems,proto3" json:"ok_items,omitempty"`
	FailedItems   []*ReserveFailedItem   `protobuf:"bytes,2,rep,name=failed_items,json=failedItems,proto3" json:"failed_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{25}
}

func (x *ReserveResponse) GetOkItems() []*ReserveOkItem {
	if x != nil {
		return x.OkItems
	}
	return nil
}

func (x *ReserveResponse) GetFailedItems() []*ReserveFailedItem {
	if x != nil {
		return x.FailedItems
	}
	return nil
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.UUID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{26}
}

func (x *ReleaseRequest) GetOrderId() *v1.UUID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       *v1.UUID               `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{27}
}

func (x *ConfirmRequest) GetOrderId() *v1.UUID {
	if x != nil {
		return x.OrderId
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\"\xbf\x03\n" +
	"\aProduct\x12(\n" +
	"\x02id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDR\x02id\x125\n" +
	"\tvendor_id\x18\x02 \x01(\v2\x18.orderhub.common.v1.UUIDR\bvendorId\x12\x1b\n" +
	"\x03sku\x18\x03 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x03sku\x12\x1e\n" +
	"\x04name\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x04name\x12*\n" +
	"\vdescription\x18\x05 \x01(\tB\b\xfaB\x05r\x03\x18\xa0 R\vdescription\x12(\n" +
	"\vprice_cents\x18\x06 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\n" +
	"priceCents\x12-\n" +
	"\rcurrency_code\x18\a \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\fcurrencyCode\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xae\x02\n" +
	"\fProductInput\x12?\n" +
	"\tvendor_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\bvendorId\x12\x1b\n" +
	"\x03sku\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\x01\x18@R\x03sku\x12\x1e\n" +
	"\x04name\x18\x03 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x04name\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xfaB\x05r\x03\x18\xa0 R\vdescription\x12(\n" +
	"\vprice_cents\x18\x05 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\n" +
	"priceCents\x12-\n" +
	"\rcurrency_code\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x98\x01\x03R\fcurrencyCode\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"\x9e\x03\n" +
	"\fProductPatch\x129\n" +
	"\x03sku\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueB\t\xfaB\x06r\x04\x10\x01\x18@R\x03sku\x12<\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x04name\x12H\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueB\b\xfaB\x05r\x03\x18\xa0 R\vdescription\x12E\n" +
	"\vprice_cents\x18\x04 \x01(\v2\x1b.google.protobuf.Int64ValueB\a\xfaB\x04\"\x02(\x00R\n" +
	"priceCents\x12K\n" +
	"\rcurrency_code\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueB\b\xfaB\x05r\x03\x98\x01\x03R\fcurrencyCode\x127\n" +
	"\tis_active\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\bisActive\"V\n" +
	"\x14CreateProductRequest\x12>\n" +
	"\aproduct\x18\x01 \x01(\v2\x1a.inventory.v1.ProductInputB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aproduct\"H\n" +
	"\x15CreateProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.inventory.v1.ProductR\aproduct\"\x95\x01\n" +
	"\x14UpdateProductRequest\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\x12:\n" +
	"\x05patch\x18\x02 \x01(\v2\x1a.inventory.v1.ProductPatchB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x05patch\"H\n" +
	"\x15UpdateProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.inventory.v1.ProductR\aproduct\"Y\n" +
	"\x14DeleteProductRequest\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\"V\n" +
	"\x11GetProductRequest\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\"E\n" +
	"\x12GetProductResponse\x12/\n" +
	"\aproduct\x18\x01 \x01(\v2\x15.inventory.v1.ProductR\aproduct\"\xd1\x01\n" +
	"\x13ListProductsRequest\x125\n" +
	"\tvendor_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDR\bvendorId\x12 \n" +
	"\x05query\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xff\x01R\x05query\x12\x1f\n" +
	"\vonly_active\x18\x03 \x01(\bR\n" +
	"onlyActive\x12\x1f\n" +
	"\x05limit\x18\n" +
	" \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\x05limit\x12\x1f\n" +
	"\x06offset\x18\v \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x06offset\"\x80\x01\n" +
	"\x14ListProductsResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.inventory.v1.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\x05R\n" +
	"nextOffset\"^\n" +
	"\x17BatchGetProductsRequest\x12C\n" +
	"\vproduct_ids\x18\x01 \x03(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x92\x01\x02\b\x01R\n" +
	"productIds\"M\n" +
	"\x18BatchGetProductsResponse\x121\n" +
	"\bproducts\x18\x01 \x03(\v2\x15.inventory.v1.ProductR\bproducts\"\xb5\x01\n" +
	"\x05Stock\x127\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDR\tproductId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x05R\tavailable\x12\x1a\n" +
	"\breserved\x18\x03 \x01(\x05R\breserved\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"T\n" +
	"\x0fGetStockRequest\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\"=\n" +
	"\x10GetStockResponse\x12)\n" +
	"\x05stock\x18\x01 \x01(\v2\x13.inventory.v1.StockR\x05stock\"{\n" +
	"\x0fSetStockRequest\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\x12%\n" +
	"\tavailable\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\tavailable\"=\n" +
	"\x10SetStockResponse\x12)\n" +
	"\x05stock\x18\x01 \x01(\v2\x13.inventory.v1.StockR\x05stock\"m\n" +
	"\x12AdjustStockRequest\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x05R\x05delta\"@\n" +
	"\x13AdjustStockResponse\x12)\n" +
	"\x05stock\x18\x01 \x01(\v2\x13.inventory.v1.StockR\x05stock\"u\n" +
	"\vReserveItem\x12A\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\tproductId\x12#\n" +
	"\bquantity\x18\x02 \x01(\rB\a\xfaB\x04*\x02 \x00R\bquantity\"\x8a\x01\n" +
	"\x0eReserveRequest\x12=\n" +
	"\border_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aorderId\x129\n" +
	"\x05items\x18\x02 \x03(\v2\x19.inventory.v1.ReserveItemB\b\xfaB\x05\x92\x01\x02\b\x01R\x05items\"d\n" +
	"\rReserveOkItem\x127\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"\x8c\x01\n" +
	"\x11ReserveFailedItem\x127\n" +
	"\n" +
	"product_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDR\tproductId\x12\x1c\n" +
	"\trequested\x18\x02 \x01(\tR\trequested\x12 \n" +
	"\x06reason\x18\x03 \x01(\tB\b\xfaB\x05r\x03\x18\xc8\x01R\x06reason\"\x8d\x01\n" +
	"\x0fReserveResponse\x126\n" +
	"\bok_items\x18\x01 \x03(\v2\x1b.inventory.v1.ReserveOkItemR\aokItems\x12B\n" +
	"\ffailed_items\x18\x02 \x03(\v2\x1f.inventory.v1.ReserveFailedItemR\vfailedItems\"O\n" +
	"\x0eReleaseRequest\x12=\n" +
	"\border_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aorderId\"O\n" +
	"\x0eConfirmRequest\x12=\n" +
	"\border_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\aorderId2\xd2\a\n" +
	"\x10InventoryService\x12X\n" +
	"\rCreateProduct\x12\".inventory.v1.CreateProductRequest\x1a#.inventory.v1.CreateProductResponse\x12X\n" +
	"\rUpdateProduct\x12\".inventory.v1.UpdateProductRequest\x1a#.inventory.v1.UpdateProductResponse\x12O\n" +
	"\n" +
	"GetProduct\x12\x1f.inventory.v1.GetProductRequest\x1a .inventory.v1.GetProductResponse\x12U\n" +
	"\fListProducts\x12!.inventory.v1.ListProductsRequest\x1a\".inventory.v1.ListProductsResponse\x12K\n" +
	"\rDeleteProduct\x12\".inventory.v1.DeleteProductRequest\x1a\x16.google.protobuf.Empty\x12a\n" +
	"\x10BatchGetProducts\x12%.inventory.v1.BatchGetProductsRequest\x1a&.inventory.v1.BatchGetProductsResponse\x12I\n" +
	"\bGetStock\x12\x1d.inventory.v1.GetStockRequest\x1a\x1e.inventory.v1.GetStockResponse\x12I\n" +
	"\bSetStock\x12\x1d.inventory.v1.SetStockRequest\x1a\x1e.inventory.v1.SetStockResponse\x12R\n" +
	"\vAdjustStock\x12 .inventory.v1.AdjustStockRequest\x1a!.inventory.v1.AdjustStockResponse\x12F\n" +
	"\aReserve\x12\x1c.inventory.v1.ReserveRequest\x1a\x1d.inventory.v1.ReserveResponse\x12?\n" +
	"\aRelease\x12\x1c.inventory.v1.ReleaseRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\aConfirm\x12\x1c.inventory.v1.ConfirmRequest\x1a\x16.google.protobuf.EmptyBHZFgithub.com/Anabol1ks/orderhub-pkg-proto/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(*Product)(nil),                  // 0: inventory.v1.Product
	(*ProductInput)(nil),             // 1: inventory.v1.ProductInput
	(*ProductPatch)(nil),             // 2: inventory.v1.ProductPatch
	(*CreateProductRequest)(nil),     // 3: inventory.v1.CreateProductRequest
	(*CreateProductResponse)(nil),    // 4: inventory.v1.CreateProductResponse
	(*UpdateProductRequest)(nil),     // 5: inventory.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),    // 6: inventory.v1.UpdateProductResponse
	(*DeleteProductRequest)(nil),     // 7: inventory.v1.DeleteProductRequest
	(*GetProductRequest)(nil),        // 8: inventory.v1.GetProductRequest
	(*GetProductResponse)(nil),       // 9: inventory.v1.GetProductResponse
	(*ListProductsRequest)(nil),      // 10: inventory.v1.ListProductsRequest
	(*ListProductsResponse)(nil),     // 11: inventory.v1.ListProductsResponse
	(*BatchGetProductsRequest)(nil),  // 12: inventory.v1.BatchGetProductsRequest
	(*BatchGetProductsResponse)(nil), // 13: inventory.v1.BatchGetProductsResponse
	(*Stock)(nil),                    // 14: inventory.v1.Stock
	(*GetStockRequest)(nil),          // 15: inventory.v1.GetStockRequest
	(*GetStockResponse)(nil),         // 16: inventory.v1.GetStockResponse
	(*SetStockRequest)(nil),          // 17: inventory.v1.SetStockRequest
	(*SetStockResponse)(nil),         // 18: inventory.v1.SetStockResponse
	(*AdjustStockRequest)(nil),       // 19: inventory.v1.AdjustStockRequest
	(*AdjustStockResponse)(nil),      // 20: inventory.v1.AdjustStockResponse
	(*ReserveItem)(nil),              // 21: inventory.v1.ReserveItem
	(*ReserveRequest)(nil),           // 22: inventory.v1.ReserveRequest
	(*ReserveOkItem)(nil),            // 23: inventory.v1.ReserveOkItem
	(*ReserveFailedItem)(nil),        // 24: inventory.v1.ReserveFailedItem
	(*ReserveResponse)(nil),          // 25: inventory.v1.ReserveResponse
	(*ReleaseRequest)(nil),           // 26: inventory.v1.ReleaseRequest
	(*ConfirmRequest)(nil),           // 27: inventory.v1.ConfirmRequest
	(*v1.UUID)(nil),                  // 28: orderhub.common.v1.UUID
	(*timestamppb.Timestamp)(nil),    // 29: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),   // 30: google.protobuf.StringValue
	(*wrapperspb.Int64Value)(nil),    // 31: google.protobuf.Int64Value
	(*wrapperspb.BoolValue)(nil),     // 32: google.protobuf.BoolValue
	(*emptypb.Empty)(nil),            // 33: google.protobuf.Empty
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	28, // 0: inventory.v1.Product.id:type_name -> orderhub.common.v1.UUID
	28, // 1: inventory.v1.Product.vendor_id:type_name -> orderhub.common.v1.UUID
	29, // 2: inventory.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	29, // 3: inventory.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	28, // 4: inventory.v1.ProductInput.vendor_id:type_name -> orderhub.common.v1.UUID
	30, // 5: inventory.v1.ProductPatch.sku:type_name -> google.protobuf.StringValue
	30, // 6: inventory.v1.ProductPatch.name:type_name -> google.protobuf.StringValue
	30, // 7: inventory.v1.ProductPatch.description:type_name -> google.protobuf.StringValue
	31, // 8: inventory.v1.ProductPatch.price_cents:type_name -> google.protobuf.Int64Value
	30, // 9: inventory.v1.ProductPatch.currency_code:type_name -> google.protobuf.StringValue
	32, // 10: inventory.v1.ProductPatch.is_active:type_name -> google.protobuf.BoolValue
	1,  // 11: inventory.v1.CreateProductRequest.product:type_name -> inventory.v1.ProductInput
	0,  // 12: inventory.v1.CreateProductResponse.product:type_name -> inventory.v1.Product
	28, // 13: inventory.v1.UpdateProductRequest.product_id:type_name -> orderhub.common.v1.UUID
	2,  // 14: inventory.v1.UpdateProductRequest.patch:type_name -> inventory.v1.ProductPatch
	0,  // 15: inventory.v1.UpdateProductResponse.product:type_name -> inventory.v1.Product
	28, // 16: inventory.v1.DeleteProductRequest.product_id:type_name -> orderhub.common.v1.UUID
	28, // 17: inventory.v1.GetProductRequest.product_id:type_name -> orderhub.common.v1.UUID
	0,  // 18: inventory.v1.GetProductResponse.product:type_name -> inventory.v1.Product
	28, // 19: inventory.v1.ListProductsRequest.vendor_id:type_name -> orderhub.common.v1.UUID
	0,  // 20: inventory.v1.ListProductsResponse.products:type_name -> inventory.v1.Product
	28, // 21: inventory.v1.BatchGetProductsRequest.product_ids:type_name -> orderhub.common.v1.UUID
	0,  // 22: inventory.v1.BatchGetProductsResponse.products:type_name -> inventory.v1.Product
	28, // 23: inventory.v1.Stock.product_id:type_name -> orderhub.common.v1.UUID
	29, // 24: inventory.v1.Stock.updated_at:type_name -> google.protobuf.Timestamp
	28, // 25: inventory.v1.GetStockRequest.product_id:type_name -> orderhub.common.v1.UUID
	14, // 26: inventory.v1.GetStockResponse.stock:type_name -> inventory.v1.Stock
	28, // 27: inventory.v1.SetStockRequest.product_id:type_name -> orderhub.common.v1.UUID
	14, // 28: inventory.v1.SetStockResponse.stock:type_name -> inventory.v1.Stock
	28, // 29: inventory.v1.AdjustStockRequest.product_id:type_name -> orderhub.common.v1.UUID
	14, // 30: inventory.v1.AdjustStockResponse.stock:type_name -> inventory.v1.Stock
	28, // 31: inventory.v1.ReserveItem.product_id:type_name -> orderhub.common.v1.UUID
	28, // 32: inventory.v1.ReserveRequest.order_id:type_name -> orderhub.common.v1.UUID
	21, // 33: inventory.v1.ReserveRequest.items:type_name -> inventory.v1.ReserveItem
	28, // 34: inventory.v1.ReserveOkItem.product_id:type_name -> orderhub.common.v1.UUID
	28, // 35: inventory.v1.ReserveFailedItem.product_id:type_name -> orderhub.common.v1.UUID
	23, // 36: inventory.v1.ReserveResponse.ok_items:type_name -> inventory.v1.ReserveOkItem
	24, // 37: inventory.v1.ReserveResponse.failed_items:type_name -> inventory.v1.ReserveFailedItem
	28, // 38: inventory.v1.ReleaseRequest.order_id:type_name -> orderhub.common.v1.UUID
	28, // 39: inventory.v1.ConfirmRequest.order_id:type_name -> orderhub.common.v1.UUID
	3,  // 40: inventory.v1.InventoryService.CreateProduct:input_type -> inventory.v1.CreateProductRequest
	5,  // 41: inventory.v1.InventoryService.UpdateProduct:input_type -> inventory.v1.UpdateProductRequest
	8,  // 42: inventory.v1.InventoryService.GetProduct:input_type -> inventory.v1.GetProductRequest
	10, // 43: inventory.v1.InventoryService.ListProducts:input_type -> inventory.v1.ListProductsRequest
	7,  // 44: inventory.v1.InventoryService.DeleteProduct:input_type -> inventory.v1.DeleteProductRequest
	12, // 45: inventory.v1.InventoryService.BatchGetProducts:input_type -> inventory.v1.BatchGetProductsRequest
	15, // 46: inventory.v1.InventoryService.GetStock:input_type -> inventory.v1.GetStockRequest
	17, // 47: inventory.v1.InventoryService.SetStock:input_type -> inventory.v1.SetStockRequest
	19, // 48: inventory.v1.InventoryService.AdjustStock:input_type -> inventory.v1.AdjustStockRequest
	22, // 49: inventory.v1.InventoryService.Reserve:input_type -> inventory.v1.ReserveRequest
	26, // 50: inventory.v1.InventoryService.Release:input_type -> inventory.v1.ReleaseRequest
	27, // 51: inventory.v1.InventoryService.Confirm:input_type -> inventory.v1.ConfirmRequest
	4,  // 52: inventory.v1.InventoryService.CreateProduct:output_type -> inventory.v1.CreateProductResponse
	6,  // 53: inventory.v1.InventoryService.UpdateProduct:output_type -> inventory.v1.UpdateProductResponse
	9,  // 54: inventory.v1.InventoryService.GetProduct:output_type -> inventory.v1.GetProductResponse
	11, // 55: inventory.v1.InventoryService.ListProducts:output_type -> inventory.v1.ListProductsResponse
	33, // 56: inventory.v1.InventoryService.DeleteProduct:output_type -> google.protobuf.Empty
	13, // 57: inventory.v1.InventoryService.BatchGetProducts:output_type -> inventory.v1.BatchGetProductsResponse
	16, // 58: inventory.v1.InventoryService.GetStock:output_type -> inventory.v1.GetStockResponse
	18, // 59: inventory.v1.InventoryService.SetStock:output_type -> inventory.v1.SetStockResponse
	20, // 60: inventory.v1.InventoryService.AdjustStock:output_type -> inventory.v1.AdjustStockResponse
	25, // 61: inventory.v1.InventoryService.Reserve:output_type -> inventory.v1.ReserveResponse
	33, // 62: inventory.v1.InventoryService.Release:output_type -> google.protobuf.Empty
	33, // 63: inventory.v1.InventoryService.Confirm:output_type -> google.protobuf.Empty
	52, // [52:64] is the sub-list for method output_type
	40, // [40:52] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
