// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: auth/v1/auth.proto

package authv1

import (
	v1 "github.com/Anabol1ks/orderhub-pkg-proto/proto/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *v1.UUID               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          v1.Role                `protobuf:"varint,3,opt,name=role,proto3,enum=orderhub.common.v1.Role" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() *v1.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *RegisterResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterResponse) GetRole() v1.Role {
	if x != nil {
		return x.Role
	}
	return v1.Role(0)
}

func (x *RegisterResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *v1.UUID               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          v1.Role                `protobuf:"varint,2,opt,name=role,proto3,enum=orderhub.common.v1.Role" json:"role,omitempty"`
	Tokens        *TokenPair             `protobuf:"bytes,3,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetUserId() *v1.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *LoginResponse) GetRole() v1.Role {
	if x != nil {
		return x.Role
	}
	return v1.Role(0)
}

func (x *LoginResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type TokenPair struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresIn  int64                  `protobuf:"varint,3,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`    // сек
	RefreshExpiresIn int64                  `protobuf:"varint,4,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"` // сек
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenPair) Reset() {
	*x = TokenPair{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPair) ProtoMessage() {}

func (x *TokenPair) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPair.ProtoReflect.Descriptor instead.
func (*TokenPair) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenPair) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenPair) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenPair) GetAccessExpiresIn() int64 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *TokenPair) GetRefreshExpiresIn() int64 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type IntrospectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectRequest) Reset() {
	*x = IntrospectRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectRequest) ProtoMessage() {}

func (x *IntrospectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectRequest.ProtoReflect.Descriptor instead.
func (*IntrospectRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *IntrospectRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type IntrospectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	UserId        *v1.UUID               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          v1.Role                `protobuf:"varint,3,opt,name=role,proto3,enum=orderhub.common.v1.Role" json:"role,omitempty"`
	ExpUnix       int64                  `protobuf:"varint,4,opt,name=exp_unix,json=expUnix,proto3" json:"exp_unix,omitempty"`
	Scopes        []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectResponse) Reset() {
	*x = IntrospectResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectResponse) ProtoMessage() {}

func (x *IntrospectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectResponse.ProtoReflect.Descriptor instead.
func (*IntrospectResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *IntrospectResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *IntrospectResponse) GetUserId() *v1.UUID {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *IntrospectResponse) GetRole() v1.Role {
	if x != nil {
		return x.Role
	}
	return v1.Role(0)
}

func (x *IntrospectResponse) GetExpUnix() int64 {
	if x != nil {
		return x.ExpUnix
	}
	return 0
}

func (x *IntrospectResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Target:
	//
	//	*LogoutRequest_RefreshToken
	//	*LogoutRequest_All
	Target        isLogoutRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutRequest) GetTarget() isLogoutRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		if x, ok := x.Target.(*LogoutRequest_RefreshToken); ok {
			return x.RefreshToken
		}
	}
	return ""
}

func (x *LogoutRequest) GetAll() bool {
	if x != nil {
		if x, ok := x.Target.(*LogoutRequest_All); ok {
			return x.All
		}
	}
	return false
}

type isLogoutRequest_Target interface {
	isLogoutRequest_Target()
}

type LogoutRequest_RefreshToken struct {
	RefreshToken string `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3,oneof"`
}

type LogoutRequest_All struct {
	All bool `protobuf:"varint,2,opt,name=all,proto3,oneof"`
}

func (*LogoutRequest_RefreshToken) isLogoutRequest_Target() {}

func (*LogoutRequest_All) isLogoutRequest_Target() {}

type GetJwksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJwksRequest) Reset() {
	*x = GetJwksRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJwksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksRequest) ProtoMessage() {}

func (x *GetJwksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksRequest.ProtoReflect.Descriptor instead.
func (*GetJwksRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

type Jwk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kid           string                 `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Kty           string                 `protobuf:"bytes,2,opt,name=kty,proto3" json:"kty,omitempty"`
	Alg           string                 `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
	Use           string                 `protobuf:"bytes,4,opt,name=use,proto3" json:"use,omitempty"`
	N             string                 `protobuf:"bytes,5,opt,name=n,proto3" json:"n,omitempty"`
	E             string                 `protobuf:"bytes,6,opt,name=e,proto3" json:"e,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Jwk) Reset() {
	*x = Jwk{}
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Jwk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jwk) ProtoMessage() {}

func (x *Jwk) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jwk.ProtoReflect.Descriptor instead.
func (*Jwk) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *Jwk) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *Jwk) GetKty() string {
	if x != nil {
		return x.Kty
	}
	return ""
}

func (x *Jwk) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *Jwk) GetUse() string {
	if x != nil {
		return x.Use
	}
	return ""
}

func (x *Jwk) GetN() string {
	if x != nil {
		return x.N
	}
	return ""
}

func (x *Jwk) GetE() string {
	if x != nil {
		return x.E
	}
	return ""
}

type GetJwksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Jwk                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJwksResponse) Reset() {
	*x = GetJwksResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJwksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJwksResponse) ProtoMessage() {}

func (x *GetJwksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJwksResponse.ProtoReflect.Descriptor instead.
func (*GetJwksResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{12}
}

func (x *GetJwksResponse) GetKeys() []*Jwk {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RequestEmailVerificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Если вызван авторизованным пользователем — можно не передавать email (брать из токена).
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEmailVerificationRequest) Reset() {
	*x = RequestEmailVerificationRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEmailVerificationRequest) ProtoMessage() {}

func (x *RequestEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*RequestEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RequestEmailVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ConfirmEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmEmailVerificationRequest) Reset() {
	*x = ConfirmEmailVerificationRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmEmailVerificationRequest) ProtoMessage() {}

func (x *ConfirmEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ConfirmEmailVerificationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RequestPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPasswordResetRequest) Reset() {
	*x = RequestPasswordResetRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPasswordResetRequest) ProtoMessage() {}

func (x *RequestPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*RequestPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{15}
}

func (x *RequestPasswordResetRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ConfirmPasswordResetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPasswordResetRequest) Reset() {
	*x = ConfirmPasswordResetRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPasswordResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPasswordResetRequest) ProtoMessage() {}

func (x *ConfirmPasswordResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPasswordResetRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPasswordResetRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{16}
}

func (x *ConfirmPasswordResetRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ConfirmPasswordResetRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\"Z\n" +
	"\x0fRegisterRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x18\xfe\x01`\x01R\x05email\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18HR\bpassword\"\xd7\x01\n" +
	"\x10RegisterResponse\x12;\n" +
	"\auser_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06userId\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12,\n" +
	"\x04role\x18\x03 \x01(\x0e2\x18.orderhub.common.v1.RoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"W\n" +
	"\fLoginRequest\x12 \n" +
	"\x05email\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x18\xfe\x01`\x01R\x05email\x12%\n" +
	"\bpassword\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18HR\bpassword\"\xa6\x01\n" +
	"\rLoginResponse\x12;\n" +
	"\auser_id\x18\x01 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06userId\x12,\n" +
	"\x04role\x18\x02 \x01(\x0e2\x18.orderhub.common.v1.RoleR\x04role\x12*\n" +
	"\x06tokens\x18\x03 \x01(\v2\x12.auth.v1.TokenPairR\x06tokens\"\xbf\x01\n" +
	"\tTokenPair\x12*\n" +
	"\faccess_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x10R\vaccessToken\x12,\n" +
	"\rrefresh_token\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x18R\frefreshToken\x12*\n" +
	"\x11access_expires_in\x18\x03 \x01(\x03R\x0faccessExpiresIn\x12,\n" +
	"\x12refresh_expires_in\x18\x04 \x01(\x03R\x10refreshExpiresIn\">\n" +
	"\x0eRefreshRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x18R\frefreshToken\"=\n" +
	"\x0fRefreshResponse\x12*\n" +
	"\x06tokens\x18\x01 \x01(\v2\x12.auth.v1.TokenPairR\x06tokens\"?\n" +
	"\x11IntrospectRequest\x12*\n" +
	"\faccess_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x14R\vaccessToken\"\xca\x01\n" +
	"\x12IntrospectResponse\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active\x12;\n" +
	"\auser_id\x18\x02 \x01(\v2\x18.orderhub.common.v1.UUIDB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06userId\x12,\n" +
	"\x04role\x18\x03 \x01(\x0e2\x18.orderhub.common.v1.RoleR\x04role\x12\x19\n" +
	"\bexp_unix\x18\x04 \x01(\x03R\aexpUnix\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\"]\n" +
	"\rLogoutRequest\x12.\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x18H\x00R\frefreshToken\x12\x12\n" +
	"\x03all\x18\x02 \x01(\bH\x00R\x03allB\b\n" +
	"\x06target\"\x10\n" +
	"\x0eGetJwksRequest\"\xaa\x01\n" +
	"\x03Jwk\x12\x19\n" +
	"\x03kid\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x03kid\x12\x1c\n" +
	"\x03kty\x18\x02 \x01(\tB\n" +
	"\xfaB\ar\x05R\x03RSAR\x03kty\x12\x1e\n" +
	"\x03alg\x18\x03 \x01(\tB\f\xfaB\tr\aR\x05RS256R\x03alg\x12\x1c\n" +
	"\x03use\x18\x04 \x01(\tB\n" +
	"\xfaB\ar\x05R\x03sigR\x03use\x12\x15\n" +
	"\x01n\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\n" +
	"R\x01n\x12\x15\n" +
	"\x01e\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x01e\"3\n" +
	"\x0fGetJwksResponse\x12 \n" +
	"\x04keys\x18\x01 \x03(\v2\f.auth.v1.JwkR\x04keys\"@\n" +
	"\x1fRequestEmailVerificationRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\"@\n" +
	"\x1fConfirmEmailVerificationRequest\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\n" +
	"\x18\n" +
	"R\x04code\"<\n" +
	"\x1bRequestPasswordResetRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\"j\n" +
	"\x1bConfirmPasswordResetRequest\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x06R\x04code\x12,\n" +
	"\fnew_password\x18\x02 \x01(\tB\t\xfaB\x06r\x04\x10\b\x18HR\vnewPassword2\xeb\x05\n" +
	"\vAuthService\x12?\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\x126\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12<\n" +
	"\aRefresh\x12\x17.auth.v1.RefreshRequest\x1a\x18.auth.v1.RefreshResponse\x12E\n" +
	"\n" +
	"Introspect\x12\x1a.auth.v1.IntrospectRequest\x1a\x1b.auth.v1.IntrospectResponse\x128\n" +
	"\x06Logout\x12\x16.auth.v1.LogoutRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\aGetJwks\x12\x17.auth.v1.GetJwksRequest\x1a\x18.auth.v1.GetJwksResponse\x12\\\n" +
	"\x18RequestEmailVerification\x12(.auth.v1.RequestEmailVerificationRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x18ConfirmEmailVerification\x12(.auth.v1.ConfirmEmailVerificationRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x14RequestPasswordReset\x12$.auth.v1.RequestPasswordResetRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x14ConfirmPasswordReset\x12$.auth.v1.ConfirmPasswordResetRequest\x1a\x16.google.protobuf.EmptyB>Z<github.com/Anabol1ks/orderhub-pkg-proto/proto/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_auth_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),                 // 0: auth.v1.RegisterRequest
	(*RegisterResponse)(nil),                // 1: auth.v1.RegisterResponse
	(*LoginRequest)(nil),                    // 2: auth.v1.LoginRequest
	(*LoginResponse)(nil),                   // 3: auth.v1.LoginResponse
	(*TokenPair)(nil),                       // 4: auth.v1.TokenPair
	(*RefreshRequest)(nil),                  // 5: auth.v1.RefreshRequest
	(*RefreshResponse)(nil),                 // 6: auth.v1.RefreshResponse
	(*IntrospectRequest)(nil),               // 7: auth.v1.IntrospectRequest
	(*IntrospectResponse)(nil),              // 8: auth.v1.IntrospectResponse
	(*LogoutRequest)(nil),                   // 9: auth.v1.LogoutRequest
	(*GetJwksRequest)(nil),                  // 10: auth.v1.GetJwksRequest
	(*Jwk)(nil),                             // 11: auth.v1.Jwk
	(*GetJwksResponse)(nil),                 // 12: auth.v1.GetJwksResponse
	(*RequestEmailVerificationRequest)(nil), // 13: auth.v1.RequestEmailVerificationRequest
	(*ConfirmEmailVerificationRequest)(nil), // 14: auth.v1.ConfirmEmailVerificationRequest
	(*RequestPasswordResetRequest)(nil),     // 15: auth.v1.RequestPasswordResetRequest
	(*ConfirmPasswordResetRequest)(nil),     // 16: auth.v1.ConfirmPasswordResetRequest
	(*v1.UUID)(nil),                         // 17: orderhub.common.v1.UUID
	(v1.Role)(0),                            // 18: orderhub.common.v1.Role
	(*timestamppb.Timestamp)(nil),           // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 20: google.protobuf.Empty
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	17, // 0: auth.v1.RegisterResponse.user_id:type_name -> orderhub.common.v1.UUID
	18, // 1: auth.v1.RegisterResponse.role:type_name -> orderhub.common.v1.Role
	19, // 2: auth.v1.RegisterResponse.created_at:type_name -> google.protobuf.Timestamp
	17, // 3: auth.v1.LoginResponse.user_id:type_name -> orderhub.common.v1.UUID
	18, // 4: auth.v1.LoginResponse.role:type_name -> orderhub.common.v1.Role
	4,  // 5: auth.v1.LoginResponse.tokens:type_name -> auth.v1.TokenPair
	4,  // 6: auth.v1.RefreshResponse.tokens:type_name -> auth.v1.TokenPair
	17, // 7: auth.v1.IntrospectResponse.user_id:type_name -> orderhub.common.v1.UUID
	18, // 8: auth.v1.IntrospectResponse.role:type_name -> orderhub.common.v1.Role
	11, // 9: auth.v1.GetJwksResponse.keys:type_name -> auth.v1.Jwk
	0,  // 10: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	2,  // 11: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	5,  // 12: auth.v1.AuthService.Refresh:input_type -> auth.v1.RefreshRequest
	7,  // 13: auth.v1.AuthService.Introspect:input_type -> auth.v1.IntrospectRequest
	9,  // 14: auth.v1.AuthService.Logout:input_type -> auth.v1.LogoutRequest
	10, // 15: auth.v1.AuthService.GetJwks:input_type -> auth.v1.GetJwksRequest
	13, // 16: auth.v1.AuthService.RequestEmailVerification:input_type -> auth.v1.RequestEmailVerificationRequest
	14, // 17: auth.v1.AuthService.ConfirmEmailVerification:input_type -> auth.v1.ConfirmEmailVerificationRequest
	15, // 18: auth.v1.AuthService.RequestPasswordReset:input_type -> auth.v1.RequestPasswordResetRequest
	16, // 19: auth.v1.AuthService.ConfirmPasswordReset:input_type -> auth.v1.ConfirmPasswordResetRequest
	1,  // 20: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	3,  // 21: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	6,  // 22: auth.v1.AuthService.Refresh:output_type -> auth.v1.RefreshResponse
	8,  // 23: auth.v1.AuthService.Introspect:output_type -> auth.v1.IntrospectResponse
	20, // 24: auth.v1.AuthService.Logout:output_type -> google.protobuf.Empty
	12, // 25: auth.v1.AuthService.GetJwks:output_type -> auth.v1.GetJwksResponse
	20, // 26: auth.v1.AuthService.RequestEmailVerification:output_type -> google.protobuf.Empty
	20, // 27: auth.v1.AuthService.ConfirmEmailVerification:output_type -> google.protobuf.Empty
	20, // 28: auth.v1.AuthService.RequestPasswordReset:output_type -> google.protobuf.Empty
	20, // 29: auth.v1.AuthService.ConfirmPasswordReset:output_type -> google.protobuf.Empty
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	file_auth_v1_auth_proto_msgTypes[9].OneofWrappers = []any{
		(*LogoutRequest_RefreshToken)(nil),
		(*LogoutRequest_All)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
